### ISSUE TITLE
Element massNumberArray and relativeAbundanceArray should not be static

### ISSUE THREAD

**Issue by DennisGoldfarb** [optimusmoose/JAMSS#1]
Since the variables for Element.massNumberArray and Element.relativeAbundanceArray are currently static, only one instance exists for all Elements, but in reality each Element should have its own instance of those variables. In MassSpec.java lines 421 to 441, each Element is initialized with different values, but since the variables are static, all Elements (O,N,C,H,S,P,Se) have the same value for them. With Se being the last Element initialized, all the elements have their isotope masses equal to {74, 76, 77, 78, 80, 82} and relative abundances set to {0.0089, 0.0937, 0.0763, 0.2377, 0.4961, 0.0873}. 

The downstream consequences are that the calculated isotopic distributions are incorrect. Removing the static keyword from the two variables resolves the problem and the distributions are fine.

**Comment by optimusmoose** [comment]
Good catch. Fixed. If I remember, the original idea was to save space by making the elements static, with each element being it's own class. I think the classes were later merged without catching the effect of the static vars. 

Thanks again.
